# fly.toml file generated for customsurviv on 2023-04-25T21:17:41+01:00

app = "customsurviv"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"

[env]
  PORT = "8000"
  WS_PORT = "8001"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 8001

  [[services.ports]]
    port = 444
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
